#!/usr/bin/env python
import asyncio
import logging
from infra.clients import registry as client_registry


def main():
    client = client_registry.get()
    client.start_client()


if __name__ == "__main__":
    main()
