clients:
    type: base
    total_clients: 400
    num_physical_clients: 400
    worst_online_frac: 1.0
#    resource_saving: true
    sample:
        type: uniform
        mode: fixed_sample_size
        sample_size: 40
        seed: 1
        security:
            type: client_centric
            min_accepted_population: 400
            over_selection_factor: 2
            randomness_simulator:
                type: os_random
            pki_simulator:
                type: elliptic_curve  # follow key agreement
            verifiable_random_function:
                type: basic
            signature:
                type: ed25519
            informed:
                type: or
                metric:
                    - type: slowest_speed
                      percentile: 20
                    - type: poorest_data
                      percentile: 20
        mock: true  # so that different approaches are comparable (after accounting for client heterogeneity)
server:
    type: base
    address: 127.0.0.1
    port:
        - 8000
        - 8001
        - 8002
        - 8003
        - 8004
        - 8005
        - 8006
        - 8007
        - 8008
        - 8009
        - 8010
        - 8011
        - 8012
        - 8013
        - 8014
        - 8015
    disable_clients: true
    ping_interval: 1
    ping_timeout: 86400
    redis:
        port: 6379

scheduler:
    type: base

agg:
    type: secagg
    threshold: 0.5
    security:
        bit_width: 20
        key_agreement:
            type: elliptic_curve
        secret_sharing:
            type: myshamir
            threshold: 0.5
        authenticated_encryption:
            type: fernet
        pseudorandom_generator:
            type: os_random
    quantize:
        type: asymmetric
        clipping_range:
            - -3.0
            - 3.0
        bit_width: 20
        batch:
            type: best
            total_bit_width: 60

app:
    type: federated_learning
    init_scale_threshold: 1.0
    repeat: 3
    debug:
        client:
            sketch_num: 3
        server:
            sketch_num: 3
            test: true
    data:
        random_seed: 1
        datasource: openImage
        sampler: all_inclusive
        concurrent_download: True
    trainer:
        epochs: 3
        batch_size: 20
        type: basic
        model_name: mobilenet_v2_wd4
        optimizer: SGD
        learning_rate: 0.05
        momentum: 0.9
        weight_decay: 0
        num_classes: 596
        test_batch_size: 20
        lr_schedule: StepLR
        lr_step_size: 10
        lr_gamma: 0.98

results:
    results_dir: ./
    types: round_time