clients:
    type: base
    total_clients: 700
    num_physical_clients: 70
    resource_saving: true
    worst_online_frac: 1.0  # placeholder for using fixed_sample_size, no real use
    sample:
        type: uniform
        mode: fixed_sample_size
        sample_size: 70
        seed: 1
        preclude_clients:
            - type: poorest_data
              percentile: 20
            - type: slowest_speed
              percentile: 20
simulation:
    type: simple
    time:
        print_virtual_time: true
        type: zipf
        a: 1.2
        min: 20
        max: 180
        seed: 1
        inflation_factor: 1.053
server:
    type: base
    address: 127.0.0.1
    port:
        - 8000
        - 8001
        - 8002
        - 8003
        - 8004
        - 8005
        - 8006
        - 8007
        - 8008
        - 8009
        - 8010
        - 8011
        - 8012
        - 8013
        - 8014
        - 8015
    disable_clients: true
    ping_interval: 1
    ping_timeout: 86400
    redis:
        port: 6379

scheduler:
    type: base

agg:
    type: plaintext
    threshold: 0.5

app:
    type: federated_learning
    init_scale_threshold: 1.0
    repeat: 100
    debug:
        client:
            sketch_num: 3
        server:
            sketch_num: 3
            test: true
    data:
        random_seed: 1
        datasource: openImage
        sampler: all_inclusive
        concurrent_download: True
    trainer:
        epochs: 3
        batch_size: 20
        type: basic
        model_name: mobilenet_v2_wd4
        optimizer: SGD
        learning_rate: 0.05
        momentum: 0.9
        weight_decay: 0
        num_classes: 596
        test_batch_size: 20
        lr_schedule: StepLR
        lr_step_size: 10
        lr_gamma: 0.98

results:
    results_dir: ./
    types: round_time
    model_save_interval: 5
    model_save_dir: ./pretrained_models/16_openimage_70_in_700/ex_last20or
